title: قناة حدث الشامية

avatar: "/assets/img/logo.jpg"

round-avatar: true

title-img: "/assets/img/logo.jpg"

social-network-links:

  facebook: hadath.alshamya
#  github: daattali
#  twitter: daattali
#  patreon: DeanAttali
  youtube: @hadath.alshamya 
#  medium: yourname
#  reddit: yourname
#  linkedin: daattali
#  xing: yourname
#  stackoverflow: "3943160/daattali"
#  snapchat: deanat78
#  instagram: deanat78
#  spotify: yourname
  telephone: +9647826270071
#  steam: deanat78
#  twitch: yourname
#  yelp: yourname
  telegram: HadathAlshamya
#  calendly: yourname
#  mastodon: instance.url/@username
#  ORCID: your ORCID ID
#  google-scholar: your google scholar
#  discord: invite/invite_code or users/userid 
#  kaggle: yourname
#  hackerrank: yourname

excerpt_length: 50

feed_show_excerpt: true

feed_show_tags: true

post_search: false

edit_page_button: false

navbar-var-length: false

navbar-col: "#000000"
navbar-text-col: "#EBB42B"
navbar-border-col: "#000000"
page-col: "#000000"
text-col: "#EBB42B"
link-col: "#c90606"
hover-col: "#0085A1"
footer-col: "#000000"
footer-text-col: "#EBB42B"
footer-link-col: "#c90606"
footer-hover-col: "#EBB42B"

navbar-img: "/assets/img/bgimage.png"
footer-img: "/assets/img/bgimage.png"
page-img: "/assets/img/bgimage.png"

date_format: "%B %-d, %Y"

mobile-theme-col: "#0085A1"

site-css:
  - "/assets/css/custom-styles.css"
site-js:
  - "/assets/js/custom-script.js"

timezone: "America/Toronto"
markdown: kramdown
highlighter: rouge
permalink: /:year-:month-:day-:title/
paginate: 5

kramdown:
  input: GFM

defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
      #comments: true  # add comments to all blog posts
      #social-share: true # add social media sharing buttons to all blog posts
  -
    scope:
      path: "" # any file that's not a post will be a "page" layout by default
    values:
      layout: "page"

exclude:
  - CHANGELOG.md
  - CNAME
  - Gemfile
  - Gemfile.lock
  - LICENSE
  - README.md
  - screenshot.png
  - docs/

plugins:
  - jekyll-paginate
  - jekyll-sitemap
